### PR TITLE
fix: build error by importing from deno_blog main

### LINKED ISSUE #1: Build fail
https://github.com/denoland/deno_blog/issues/154#issuecomment-2613119888

Looks like a problem with `deno_blog` version as is very old and missing crucial stuff... the fact that they suggest pointing to main, as is fixed there, for bugs that are known to be broken for a while may make you reconsider using this.

However I managed to fix the build, will PR.

### PR DESCRIPTION
**Pull request by adriangalilea**
Fixes #1

### CODE REVIEW

File: main.tsx [hunk 1]
```diff
@@ -1,10 +1,10 @@
 /** @jsx h */
 
-import blog from "https://raw.githubusercontent.com/denoland/deno_blog/571a875d774c4043fb0c196134dfac01a2209746/blog.tsx";
+import blog from "https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx";
```
Comment (KnorpelSenf) [inline main.tsx]:
```suggestion
import blog from "https://raw.githubusercontent.com/denoland/deno_blog/589c4750d001ae2a4e921385be558d97060e3933/blog.tsx";
```

File: main.tsx [hunk 2]
```diff
@@ -1,10 +1,10 @@
...
 import {
   h,
   type VNode,
-} from "https://raw.githubusercontent.com/denoland/deno_blog/571a875d774c4043fb0c196134dfac01a2209746/deps.ts";
+} from "https://raw.githubusercontent.com/denoland/deno_blog/main/deps.ts";
```
Comment (KnorpelSenf) [inline main.tsx]:
```suggestion
} from "https://raw.githubusercontent.com/denoland/deno_blog/589c4750d001ae2a4e921385be558d97060e3933/deps.ts";
```

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Let's maybe keep immutable deps :)

**Review by KnorpelSenf — APPROVED** [review]
LGTM, thanks!
